server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservicio-usuario
          uri: lb://microservicio-usuario
          predicates:
            - Path=/usuario/**
        - id: microservicio-carro
          uri: lb://microservicio-carro
          predicates:
            - Path=/carro/**
        - id: microservicio-moto
          uri: lb://microservicio-moto
          predicates:
            - Path=/moto/**

  