server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservicio
          uri: lb://microservicio
          predicates:
            - Path=/usuario/**
        - id: microservicio2
          uri: lb://microservicio2
          predicates:
            - Path=/carro/**
        - id: microservicio3
          uri: lb://microservicio3
          predicates:
            - Path=/moto/**

  