server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label : eureka #La rama donde están los archivos
          uri: https://github.com/JohanPineda20/microservicios #El repositorio
          search-paths: config #Carpeta donde estan todos los archivos de config de cada microservicio
  application:
    name: config-server
